[dmenu]
dmenu_command = rofi -dmenu -i -theme "$HOME/.config/rofi/themes/network.rasi"
# # Note that dmenu_command can contain arguments as well like:
# # `dmenu_command = rofi -dmenu -i -theme nmdm`
# # `dmenu_command = rofi -dmenu -width 30 -i`
# # `dmenu_command = dmenu -i -l 25 -b -nb #909090 -nf #303030`
# rofi_highlight = <True or False> # (Default: False) use rofi highlighting instead of '=='

#compact = <True or False> # (Default: False). Remove extra spacing from display

# pinentry = <Pinentry command>  # (Default: None) e.g. `pinentry-gtk`
wifi_chars = ▂▄▆█
list_saved = True


[dmenu_passphrase]
obscure = True
obscure_color = #222222

[editor]
terminal = kitty
gui_if_available = True
